### ISSUE TITLE
Add --justbuild tests

### ISSUE THREAD

**Issue by shazron** [purplecabbage/cordova-paramedic#16]
1. Expect build success (use test plugin that is known to build) Return code == 0
2. Expect build fail (use test plugin that is known to fail) Return code > 0

Need a way to verify that --justbuild works as expected.

**Comment by shazron** [comment]
In progress: https://github.com/shazron/cordova-paramedic/tree/justbuild_tests (added iOS failed build plugin)
Will send PR when done.

**Comment by purplecabbage** [comment]
Still working on this?

**Comment by shazron** [comment]
not sure where this is at. there is some work
