### ISSUE TITLE
--justBuild does not honour timeout

### ISSUE THREAD

**Issue by shazron** [purplecabbage/cordova-paramedic#25]
like the subject says.

Test on "com.timflapper.spotify@0.1.0" plugin.
It halts on stdin input in the plugin hook.

**Comment by purplecabbage** [comment]
I spelt it the american way!

**Comment by shazron** [comment]
:+1:

**Comment by shazron** [comment]
Unfortunately when I tested this today, it didn't work. I had a 60000 ms timeout, and it still hung. I sent a PR #26 with a sh-read-input plugin that will illustrate this:

```
./main.js --platform ios --plugin spec/sh-read-input-plugin/ --justbuild --timeout 60000
```
