### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by hypery2k** [purplecabbage/cordova-paramedic#27]
Are there any plans to support Android?

**Comment by vjrantal** [comment]
I have used the project successfully also on Android.

Posting the test results from Android emulator to the local server required a hard-coded IP address and I solved it in my fork by allowing one to pass the server IP as an argument https://github.com/vjrantal/cordova-paramedic/commit/c7ad59ac25716fe49cc040d9130fa52437754929. The address to use from emulator to host machine is 10.0.2.2 (source: http://developer.android.com/tools/devices/emulator.html#networkaddresses).

**Comment by xVir** [comment]
@vjrantal What about Pull Request? ;-)

**Comment by vjrantal** [comment]
Just noticed that the Android emulator case should be already handled (https://github.com/purplecabbage/cordova-paramedic/blob/0818793d1e35d7ece9bec250c593ef6d192165cc/paramedic.js#L146).

@purplecabbage Related this, I used CircleCI to build our plugin for Android (see https://github.com/AllJoyn-Cordova/cordova-plugin-alljoyn/blob/master/circle.yml). Something like that could be added to this project as well to continuously verify the Android support.

**Comment by xVir** [comment]
Great! Thank you! :-)

**Comment by purplecabbage** [comment]
Yes, indeed `--platform android` is supported.
